### ISSUE TITLE
Duplicate definition of RMRemoting.RegisterResource 

### ISSUE THREAD

**Issue by PangXing** [seata/seata-go#9]
**What happened**:
Duplicate definition of RMRemoting.RegisterResource  in package of pkg/rm/common/remoting
![image](https://user-images.githubusercontent.com/9207285/173474726-808e1a76-09e7-480b-8ba7-33b3d2f54876.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by luky116** [comment]
目录结构，今天会再优化下
